databases:
  - name: powersync-db
    databaseName: powersync
    user: powersync
    plan: free

services:
  - type: web
    name: powersync-service
    env: docker
    dockerfilePath: Dockerfile.powersync
    plan: free
    envVars:
      - key: PS_DATA_SOURCE_URI
        sync: false
      - key: PS_PG_URI
        fromDatabase:
          name: powersync-db
          property: internalConnectionString
      - key: PS_PORT
        value: "8080"
