/** API path constants — base URL from VITE_API_BASE_URL (proxied to Next.js in dev). */

export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    signup: '/auth/signup',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    resetPassword: '/auth/reset-password',
  },
  theologyClasses: '/theology-classes',
  students: '/students',
  student: (id: string) => `/students/${id}`,
  teachers: '/teachers',
  teacher: (id: string) => `/teachers/${id}`,
  classes: '/classes',
  subjects: '/subjects',
  marks: '/marks',
  marksHistory: (studentId: string) => `/marks/history/${studentId}`,
  reports: '/reports/history',
  reportGenerate: '/reports/generate',
  reportPreview: (id: string) => `/reports/${id}/preview`,
  reportDownload: (id: string) => `/reports/${id}/download`,
  enrollments: '/enrollments',
  report: '/report',
  terms: '/terms',
  settingsTerms: '/settings/terms',
  settings: {
    school: '/settings/school',
    user: '/settings/user',
    userPassword: '/settings/user/password',
    userAvatar: '/settings/user/avatar',
  },
  signatures: '/signatures',
  signaturesUpload: '/signatures/upload',
  documents: '/documents',
  documentsUpload: '/documents/upload',
  analytics: {
    dashboard: '/analytics/dashboard',
    performance: '/analytics/charts/performance',
    attendance: '/analytics/charts/attendance',
  },
  notifications: '/notifications',
  notificationsUnread: '/notifications/unread-count',
  notificationRead: (id: string | number) => `/notifications/${id}/mark-read`,
  activity: '/activity',
} as const
